"""Make payment enrollment_id nullable

Revision ID: 4b2de4321703
Revises: 651e9acae73c
Create Date: 2026-08-13 08:52:20.840893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2de4321703'
down_revision: Union[str, None] = '651e9acae73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'enrollment_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'enrollment_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
