"""Add companies and company_id to students and payments

Revision ID: 651e9acae73c
Revises: b0bb453e4f0c
Create Date: 2026-08-13 08:46:15.585978

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '651e9acae73c'
down_revision: str | None = 'b0bb453e4f0c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('trade_name', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('rh_name', sa.String(), nullable=True),
    sa.Column('rh_email', sa.String(), nullable=True),
    sa.Column('rh_phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cnpj'), 'companies', ['cnpj'], unique=True)
    op.add_column('payments', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'payments', 'companies', ['company_id'], ['id'])
    op.add_column('students', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'students', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'company_id')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'company_id')
    op.drop_index(op.f('ix_companies_cnpj'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
