"""Add companies and company_id to students and payments

Revision ID: 651e9acae73c
Revises: b0bb453e4f0c
Create Date: 2026-08-13 08:46:15.585978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '651e9acae73c'
down_revision: Union[str, None] = 'b0bb453e4f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('trade_name', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('rh_name', sa.String(), nullable=True),
    sa.Column('rh_email', sa.String(), nullable=True),
    sa.Column('rh_phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cnpj'), 'companies', ['cnpj'], unique=True)
    op.add_column('payments', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_payments_company_id', 'payments', 'companies', ['company_id'], ['id'])
    op.add_column('students', sa.Column('company_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_students_company_id', 'students', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text(
        "ALTER TABLE students DROP CONSTRAINT IF EXISTS fk_students_company_id, "
        "DROP CONSTRAINT IF EXISTS students_company_id_fkey"
    ))
    op.drop_column('students', 'company_id')
    op.execute(sa.text(
        "ALTER TABLE payments DROP CONSTRAINT IF EXISTS fk_payments_company_id, "
        "DROP CONSTRAINT IF EXISTS payments_company_id_fkey"
    ))
    op.drop_column('payments', 'company_id')
    op.drop_index(op.f('ix_companies_cnpj'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
