"""add uq enrollment student class

Revision ID: 844b5516b310
Revises: 72ddbcd675ca
Create Date: 2026-08-13 17:33:27.595717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.migration_reconcile import reconcile_enrollments


# revision identifiers, used by Alembic.
revision: str = '844b5516b310'
down_revision: Union[str, None] = '72ddbcd675ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Reconcilia duplicatas de forma segura, escolhendo a matrícula canônica e
    # abortando quando não for possível resolver automaticamente.
    conn = op.get_bind()
    reconcile_enrollments(conn)
    op.create_unique_constraint('uq_enrollment_student_class', 'enrollments', ['student_id', 'class_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_enrollment_student_class', 'enrollments', type_='unique')
    # ### end Alembic commands ###
