"""add uq enrollment student class

Revision ID: 844b5516b310
Revises: 72ddbcd675ca
Create Date: 2026-08-13 17:33:27.595717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844b5516b310'
down_revision: Union[str, None] = '72ddbcd675ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Remove matrículas duplicadas, mantendo a de menor id
    op.execute(
        sa.text(
            "DELETE FROM enrollments a USING enrollments b "
            "WHERE a.student_id = b.student_id AND a.class_id = b.class_id AND a.id > b.id"
        )
    )
    op.create_unique_constraint('uq_enrollment_student_class', 'enrollments', ['student_id', 'class_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_enrollment_student_class', 'enrollments', type_='unique')
    # ### end Alembic commands ###
