"""add plan and tenant subscription models

Revision ID: c54ab278930a
Revises: 697853c1effe
Create Date: 2026-08-15 09:05:36.711765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54ab278930a'
down_revision: Union[str, None] = '697853c1effe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('billing_cycle', sa.String(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_courses', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_tenant_id'), 'plans', ['tenant_id'], unique=False)
    op.create_table('tenant_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('mercado_pago_id', sa.String(), nullable=True),
    sa.Column('external_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_subscriptions_plan_id'), 'tenant_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_tenant_id'), 'tenant_subscriptions', ['tenant_id'], unique=False)

    op.execute('ALTER TABLE plans ENABLE ROW LEVEL SECURITY')
    op.execute("DROP POLICY IF EXISTS tenant_isolation_plans ON plans")
    op.execute(
        "CREATE POLICY tenant_isolation_plans ON plans "
        "FOR ALL TO public "
        "USING (current_setting('app.bypass_rls', true) = '1' "
        "OR tenant_id = current_setting('app.current_tenant', true)::UUID) "
        "WITH CHECK (current_setting('app.bypass_rls', true) = '1' "
        "OR tenant_id = current_setting('app.current_tenant', true)::UUID)"
    )

    op.execute('ALTER TABLE tenant_subscriptions ENABLE ROW LEVEL SECURITY')
    op.execute("DROP POLICY IF EXISTS tenant_isolation_tenant_subscriptions ON tenant_subscriptions")
    op.execute(
        "CREATE POLICY tenant_isolation_tenant_subscriptions ON tenant_subscriptions "
        "FOR ALL TO public "
        "USING (current_setting('app.bypass_rls', true) = '1' "
        "OR tenant_id = current_setting('app.current_tenant', true)::UUID) "
        "WITH CHECK (current_setting('app.bypass_rls', true) = '1' "
        "OR tenant_id = current_setting('app.current_tenant', true)::UUID)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS tenant_isolation_tenant_subscriptions ON tenant_subscriptions")
    op.execute("ALTER TABLE tenant_subscriptions DISABLE ROW LEVEL SECURITY")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_plans ON plans")
    op.execute("ALTER TABLE plans DISABLE ROW LEVEL SECURITY")
    op.drop_index(op.f('ix_tenant_subscriptions_tenant_id'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_plan_id'), table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_index(op.f('ix_plans_tenant_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
