<template>
  <div class="space-y-6"><div><p class="text-sm text-primary-600 font-medium">Certificação</p><h1 class="text-3xl font-bold">Certificados confiáveis</h1><p class="mt-1 text-gray-600">Revogação e reemissão preservam histórico e código de validação de cada versão.</p></div><div v-if="error" class="rounded-lg bg-red-50 p-3 text-red-700">{{ error }}</div><section class="rounded-xl border bg-white overflow-hidden"><div v-if="loading" class="p-8 text-gray-500">Carregando…</div><div v-else class="divide-y"><article v-for="cert in certificates" :key="cert.id" class="p-5"><div class="flex flex-col lg:flex-row gap-4"><div class="flex-1"><div class="flex flex-wrap items-center gap-2"><p class="font-semibold">{{ cert.certificate_number }}</p><span class="text-xs px-2 py-1 rounded-full" :class="badge(cert)">{{ effective(cert) }}</span><span class="text-xs text-gray-500">v{{ cert.version }}</span></div><p class="text-sm text-gray-500 mt-1">Código {{ cert.validation_code }} · emissão {{ date(cert.issued_at) }} · validade {{ date(cert.expires_at) }}</p><p v-if="cert.revocation_reason" class="text-sm text-red-700 mt-2">{{ cert.revocation_reason }}</p></div><div class="min-w-[280px] grid gap-2"><input v-model="notes[cert.id]" placeholder="Motivo da operação" class="rounded-lg border-gray-300 text-sm"/><div class="flex gap-2"><button v-if="effective(cert)==='ACTIVE'" :disabled="!validNote(cert.id)" @click="revoke(cert)" class="text-sm border border-red-200 text-red-700 rounded-lg px-3 py-2 disabled:opacity-40">Revogar</button><button v-if="['REVOKED','EXPIRED','ACTIVE'].includes(effective(cert))" :disabled="!validNote(cert.id)" @click="reissue(cert)" class="text-sm bg-primary-600 text-white rounded-lg px-3 py-2 disabled:opacity-40">Reemitir</button></div></div></div></article><div v-if="!certificates.length" class="p-8 text-gray-500">Nenhum certificado emitido.</div></div></section></div>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import { listCertificatesAdmin, reissueCertificate, revokeCertificate } from '../api/certificateOps'
const certificates=ref([]); const loading=ref(true); const error=ref(''); const notes=reactive({}); const date=v=>v?new Date(v).toLocaleDateString('pt-BR'):'Sem vencimento'; const validNote=id=>(notes[id]||'').trim().length>=3
function effective(c){ if(c.status==='REVOKED'||c.status==='SUPERSEDED') return c.status; if(c.expires_at&&new Date(c.expires_at)<=new Date()) return 'EXPIRED'; return 'ACTIVE' }
function badge(c){ const s=effective(c); return s==='ACTIVE'?'bg-green-50 text-green-700':s==='EXPIRED'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700' }
async function load(){ loading.value=true; try{ certificates.value=(await listCertificatesAdmin()).data }catch(e){ error.value=e.response?.data?.detail||'Erro ao carregar certificados.' }finally{ loading.value=false } }
async function revoke(c){ try{ Object.assign(c,(await revokeCertificate(c.id,notes[c.id])).data); notes[c.id]='' }catch(e){ error.value=e.response?.data?.detail||'Não foi possível revogar.' } }
async function reissue(c){ try{ await reissueCertificate(c.id,notes[c.id]); notes[c.id]=''; await load() }catch(e){ error.value=e.response?.data?.detail||'Não foi possível reemitir.' } }
onMounted(load)
</script>
