<template>
  <div class="space-y-7">
    <div><router-link :to="`/companies/${companyId}`" class="text-sm text-primary-600">← Voltar para empresa</router-link><h1 class="mt-2 text-3xl font-bold">Operação da empresa</h1><p class="text-gray-600">{{ company?.trade_name || company?.legal_name || 'Carregando…' }}</p></div>
    <div v-if="error" class="rounded-lg bg-red-50 p-3 text-red-700">{{ error }}</div>
    <section class="grid grid-cols-2 lg:grid-cols-6 gap-3"><Metric label="Colaboradores" :value="report.total_employees"/><Metric label="Matrículas" :value="report.total_enrollments"/><Metric label="Ativas" :value="report.active_enrollments"/><Metric label="Concluídas" :value="report.completed_enrollments"/><Metric label="Certificados" :value="report.certificates"/><Metric label="Conclusão" :value="`${report.completion_rate || 0}%`"/></section>

    <section class="grid lg:grid-cols-2 gap-5">
      <div class="rounded-xl border bg-white p-5"><h2 class="font-semibold text-lg">Convidar colaborador</h2><form class="mt-4 grid gap-3" @submit.prevent="invite"><input v-model="inviteForm.full_name" placeholder="Nome completo" class="rounded-lg border-gray-300"/><input v-model="inviteForm.cpf" placeholder="CPF (obrigatório se novo)" class="rounded-lg border-gray-300"/><input v-model="inviteForm.email" type="email" required placeholder="E-mail" class="rounded-lg border-gray-300"/><input v-model="inviteForm.phone" placeholder="Telefone" class="rounded-lg border-gray-300"/><button class="rounded-lg bg-primary-600 text-white px-4 py-2">Enviar convite</button></form></div>
      <div class="rounded-xl border bg-white p-5"><h2 class="font-semibold text-lg">Reservar vagas</h2><form class="mt-4 grid gap-3" @submit.prevent="saveSeats"><select v-model="seatForm.class_id" required class="rounded-lg border-gray-300"><option value="">Selecione a turma</option><option v-for="item in classes" :key="item.id" :value="item.id">{{ item.description || item.id }} · {{ item.status }}</option></select><input v-model.number="seatForm.seats_reserved" required type="number" min="1" placeholder="Vagas reservadas" class="rounded-lg border-gray-300"/><input v-model="seatForm.notes" placeholder="Observação/contrato" class="rounded-lg border-gray-300"/><button class="rounded-lg bg-primary-600 text-white px-4 py-2">Salvar reserva</button></form><div v-if="allocations.length" class="mt-4 text-sm space-y-2"><div v-for="a in allocations" :key="a.id" class="flex justify-between border-t pt-2"><span>{{ a.seats_used }}/{{ a.seats_reserved }} vagas usadas</span><span>{{ a.seats_available }} disponíveis</span></div></div></div>
    </section>

    <section class="rounded-xl border bg-white overflow-hidden"><div class="p-5 border-b flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold text-lg">Colaboradores</h2><p class="text-sm text-gray-500">Selecione colaboradores e matricule em lote.</p></div><div class="flex gap-2"><select v-model="bulkClass" class="rounded-lg border-gray-300"><option value="">Turma para matrícula</option><option v-for="item in classes" :key="item.id" :value="item.id">{{ item.description || item.id }}</option></select><button :disabled="!bulkClass || !selected.length" @click="bulkEnroll" class="rounded-lg bg-primary-600 text-white px-4 py-2 disabled:opacity-50">Matricular {{ selected.length }}</button></div></div><div class="divide-y"><div v-for="employee in employees" :key="employee.id" class="p-4 flex flex-col md:flex-row md:items-center gap-3"><input v-model="selected" type="checkbox" :value="employee.id"/><div class="flex-1"><p class="font-medium">{{ employee.full_name }}</p><p class="text-sm text-gray-500">{{ employee.email }} · {{ employee.user_active ? 'Ativo' : 'Aguardando ativação' }}</p></div><div class="flex gap-2"><button v-if="!employee.user_active" @click="resend(employee)" class="text-sm text-primary-600">Reenviar ativação</button><button @click="offboard(employee)" class="text-sm text-red-600">Desvincular</button></div></div></div></section>
  </div>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import { useRoute } from 'vue-router'; import api from '../api/client'; import Metric from '../components/OperationsMetric.vue'; import { bulkEnrollCompany, getCompanyTrainingReport, inviteCompanyEmployee, listSeatAllocations, offboardCompanyEmployee, resendCompanyActivation, saveSeatAllocation } from '../api/corporate'
const route=useRoute(); const companyId=route.params.id; const company=ref(null); const employees=ref([]); const classes=ref([]); const allocations=ref([]); const report=ref({}); const error=ref(''); const selected=ref([]); const bulkClass=ref('')
const inviteForm=reactive({full_name:'',cpf:'',email:'',phone:''}); const seatForm=reactive({class_id:'',seats_reserved:1,notes:''})
async function load(){ try{ const [c,e,cl,a,r]=await Promise.all([api.get(`/api/v1/companies/${companyId}`),api.get(`/api/v1/companies/${companyId}/employees`),api.get('/api/v1/classes/'),listSeatAllocations(companyId),getCompanyTrainingReport(companyId)]); company.value=c.data; employees.value=e.data; classes.value=cl.data; allocations.value=a.data; report.value=r.data }catch(e){ error.value=e.response?.data?.detail||'Erro ao carregar empresa.' } }
async function invite(){ try{ await inviteCompanyEmployee(companyId,{...inviteForm}); Object.assign(inviteForm,{full_name:'',cpf:'',email:'',phone:''}); await load() }catch(e){ error.value=e.response?.data?.detail||'Não foi possível convidar.' } }
async function saveSeats(){ try{ await saveSeatAllocation(companyId,{...seatForm}); await load() }catch(e){ error.value=e.response?.data?.detail||'Não foi possível reservar vagas.' } }
async function bulkEnroll(){ try{ await bulkEnrollCompany(companyId,{class_id:bulkClass.value,student_ids:selected.value}); selected.value=[]; await load() }catch(e){ error.value=e.response?.data?.detail||'Não foi possível matricular em lote.' } }
async function resend(employee){ try{ await resendCompanyActivation(companyId,employee.id) }catch(e){ error.value=e.response?.data?.detail||'Falha ao reenviar ativação.' } }
async function offboard(employee){ try{ await offboardCompanyEmployee(companyId,employee.id,{deactivate_account:false,cancel_active_corporate_enrollments:true}); await load() }catch(e){ error.value=e.response?.data?.detail||'Falha ao desvincular colaborador.' } }
onMounted(load)
</script>
