<template>
  <div :class="isAuthenticatedStudent ? '' : 'min-h-screen flex flex-col'">
    <AppNavbar v-if="!isAuthenticatedStudent" />
    <section class="brand-gradient relative overflow-hidden text-white" data-testid="catalog-header">
      <div class="absolute -right-24 -top-32 h-96 w-96 rounded-full bg-white/[.07]"></div><div class="absolute bottom-0 left-1/4 h-28 w-80 rounded-t-full bg-white/[.04]"></div>
      <div class="relative mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8"><div class="mx-auto max-w-3xl text-center"><p class="text-xs font-bold uppercase tracking-[.2em] text-white/55">Academia profissional</p><h1 class="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Cursos e Treinamentos</h1><p class="mx-auto mt-4 max-w-2xl text-sm leading-6 text-white/75 sm:text-base">Capacitação profissional em segurança, saúde, qualidade e desenvolvimento, com experiência de aprendizagem e certificação digital.</p></div></div>
    </section>
    <main class="flex-1 bg-[var(--surface-page)] py-8 sm:py-10"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="premium-toolbar mb-6 flex flex-col gap-4 p-4 lg:flex-row lg:items-center lg:justify-between" data-testid="catalog-filters"><div class="flex flex-wrap gap-2"><button v-for="cat in categories" :key="cat.key" @click="activeCategory=cat.key" :class="['rounded-xl px-4 py-2 text-xs font-bold transition',activeCategory===cat.key?'text-white shadow-sm':'border border-slate-200 bg-white text-slate-600 hover:bg-slate-50']" :style="activeCategory===cat.key?{background:'var(--brand-primary)'}:{}" :data-testid="'catalog-filter-'+cat.key">{{ cat.label }}</button></div><div class="relative w-full lg:w-80"><input v-model="searchQuery" type="text" placeholder="Buscar por curso, NR ou categoria..." class="w-full py-2.5 pl-10 pr-4 text-sm" data-testid="catalog-search"/><NavIcon name="search" class="pointer-events-none absolute left-3 top-2.5 text-slate-400"/></div></div>
      <div class="mb-5 flex items-end justify-between gap-4"><div><p class="premium-kicker">Catálogo</p><h2 class="mt-1 text-lg font-bold text-slate-900">Treinamentos disponíveis</h2></div><p class="text-xs font-semibold text-slate-400" data-testid="catalog-count">{{ filteredCourses.length }} curso{{ filteredCourses.length!==1?'s':'' }} disponíve{{ filteredCourses.length!==1?'is':'l' }}</p></div>
      <div v-if="loading" class="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3" data-testid="catalog-loading" aria-busy="true"><div v-for="n in 6" :key="n" class="premium-card overflow-hidden"><div class="aspect-video animate-pulse bg-slate-200"></div><div class="space-y-3 p-5"><div class="h-3 w-1/4 animate-pulse rounded bg-slate-200"></div><div class="h-5 w-3/4 animate-pulse rounded bg-slate-200"></div><div class="h-3 w-1/2 animate-pulse rounded bg-slate-100"></div></div></div></div>
      <div v-else-if="loadError" class="premium-card mx-auto max-w-md p-8 text-center" data-testid="catalog-error"><div class="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-red-50 text-red-600">!</div><p class="mt-4 font-bold text-slate-900">Não foi possível carregar os cursos.</p><p class="mt-1 text-sm text-slate-500">Verifique sua conexão e tente novamente.</p><button @click="loadCourses" class="mt-5 rounded-xl px-5 py-2.5 text-sm font-bold text-white" :style="{background:'var(--brand-primary)'}">Tentar novamente</button></div>
      <div v-else-if="filteredCourses.length" class="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3" data-testid="catalog-grid"><article v-for="course in filteredCourses" :key="course.id" class="premium-card premium-card-hover group flex overflow-hidden flex-col"><div class="relative overflow-hidden"><CourseCover :course="course" ratio="16/9" fit="cover" loading="lazy" img-test-id="catalog-cover-img" fb-test-id="catalog-cover-fallback"/><div class="absolute left-4 top-4 rounded-full bg-white/95 px-2.5 py-1 text-[10px] font-black uppercase tracking-wider text-slate-700 shadow-sm">{{ course.code }}</div></div><div class="flex flex-1 flex-col p-5"><p class="text-xs font-bold text-[var(--brand-primary)]">{{ course.category }}</p><h3 class="mt-1 line-clamp-2 text-lg font-bold leading-snug text-slate-900">{{ course.name }}</h3><p v-if="course.description" class="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{{ course.description }}</p><div class="mt-5 grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 text-xs"><div><p class="text-slate-400">Carga horária</p><p class="mt-1 font-bold text-slate-700">{{ course.carga_horaria }}h</p></div><div><p class="text-slate-400">Modalidade</p><p class="mt-1 font-bold text-slate-700">{{ formatModality(course.modality) }}</p></div></div><div class="mt-auto flex items-center justify-between pt-5"><div><p class="text-[10px] uppercase tracking-wide text-slate-400">Investimento</p><p class="mt-0.5 text-lg font-black text-slate-900">{{ formatPrice(course.price) }}</p></div><router-link :to="`/cursos/${course.id}`" class="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-bold text-white shadow-sm transition group-hover:-translate-y-px" :style="{background:'var(--brand-primary)'}">Ver detalhes <span>→</span></router-link></div></div></article></div>
      <div v-else class="premium-card mx-auto max-w-md p-8 text-center" data-testid="catalog-empty"><div class="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-500"><NavIcon name="search"/></div><p class="mt-4 font-bold text-slate-800">Nenhum curso encontrado.</p><p class="mt-1 text-sm text-slate-500">Tente ajustar os filtros ou a busca.</p></div>
    </div></main>
    <footer v-if="!isAuthenticatedStudent" class="bg-slate-950 py-8 text-white/70"><div class="mx-auto max-w-7xl px-4 text-center sm:px-6 lg:px-8"><img v-if="tenantStore.logo_white_url||tenantStore.logo_url" :src="tenantStore.logo_white_url||tenantStore.logo_url" :alt="tenantStore.name" class="mx-auto mb-4 h-9 w-auto max-w-[180px] object-contain"/><p class="text-sm font-semibold text-white/80">{{ tenantName }} — Treinamentos com certificação</p><p class="mt-2 text-xs text-white/35">&copy; {{ new Date().getFullYear() }} {{ tenantName }}. Todos os direitos reservados.</p></div></footer>
  </div>
</template>
<script setup>import{computed,onMounted,ref}from'vue';import{useTenantStore}from'../stores/tenant';import{useAuthStore}from'../stores/auth';import{fetchPublicCourses}from'../api/courses';import AppNavbar from'../components/AppNavbar.vue';import CourseCover from'../components/CourseCover.vue';import NavIcon from'../components/NavIcon.vue';const tenantStore=useTenantStore(),authStore=useAuthStore();const isAuthenticatedStudent=computed(()=>authStore.isAuthenticated&&authStore.userRole?.toLowerCase()==='student');const tenantName=computed(()=>tenantStore.name||'Plataforma de Cursos');const allCourses=ref([]),loading=ref(true),loadError=ref(''),activeCategory=ref('all'),searchQuery=ref('');const categories=computed(()=>{const cats=[{key:'all',label:'Todos'}],seen=new Set();for(const c of allCourses.value){if(c.category&&!seen.has(c.category)){seen.add(c.category);cats.push({key:c.category,label:c.category})}}return cats});const filteredCourses=computed(()=>{let r=allCourses.value;if(activeCategory.value!=='all')r=r.filter(c=>c.category===activeCategory.value);if(searchQuery.value.trim()){const q=searchQuery.value.toLowerCase().trim();r=r.filter(c=>(c.name||'').toLowerCase().includes(q)||(c.code||'').toLowerCase().includes(q)||(c.category||'').toLowerCase().includes(q))}return r});function formatPrice(price){if(price===0||price===null)return'Gratuito';return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(price)}function formatModality(m){return{PRESENCIAL:'Presencial',EAD:'EAD',SEMIPRESENCIAL:'Semipresencial'}[m]||m||''}async function loadCourses(){loading.value=true;loadError.value='';try{const{data}=await fetchPublicCourses();allCourses.value=Array.isArray(data)?data:[]}catch(error){allCourses.value=[];loadError.value=error.response?.data?.detail||'Erro ao carregar cursos.'}finally{loading.value=false}}onMounted(loadCourses)</script>
