<template>
  <div class="space-y-7"><div><p class="text-sm text-primary-600 font-medium">Financeiro</p><h1 class="text-3xl font-bold">Reconciliação financeira</h1><p class="mt-1 text-gray-600">Fila operacional para exceções de pagamento, chargeback e reembolso.</p></div><div v-if="error" class="rounded-lg bg-red-50 p-3 text-red-700">{{ error }}</div>
  <section class="grid grid-cols-2 lg:grid-cols-6 gap-3"><Metric label="Em aberto" :value="summary.open_reviews"/><Metric label="Em análise" :value="summary.in_review"/><Metric label="Aprovados" :value="summary.approved_payments"/><Metric label="Reembolsados" :value="summary.refunded_payments"/><Metric label="Receita líquida" :value="money(summary.net_total)"/><Metric label="Líquido no mês" :value="money(summary.monthly_net)"/></section>
  <section class="rounded-xl border bg-white overflow-hidden"><div class="p-5 border-b flex justify-between"><h2 class="font-semibold text-lg">Fila de revisão</h2><select v-model="filter" @change="loadReviews" class="rounded-lg border-gray-300"><option value="">Todas</option><option>OPEN</option><option>IN_REVIEW</option><option>RESOLVED</option><option>DISMISSED</option></select></div><div v-if="loading" class="p-8 text-gray-500">Carregando…</div><div v-else-if="!reviews.length" class="p-8 text-gray-500">Nenhuma revisão.</div><div v-else class="divide-y"><article v-for="review in reviews" :key="review.id" class="p-5"><div class="flex flex-col lg:flex-row lg:items-start gap-4"><div class="flex-1"><div class="flex flex-wrap gap-2"><span class="font-semibold">{{ review.reason }}</span><span class="text-xs rounded-full bg-gray-100 px-2 py-1">{{ review.status }}</span><span class="text-xs rounded-full bg-amber-50 px-2 py-1">{{ review.priority }}</span></div><p class="mt-2 text-sm text-gray-500">Pagamento {{ review.payment_id }} · {{ review.provider }} · {{ money(review.payment_amount) }} · {{ review.payment_status }}</p></div><button v-if="review.status==='OPEN'" @click="claim(review)" class="text-sm rounded-lg border px-3 py-2">Assumir caso</button></div><div v-if="['OPEN','IN_REVIEW'].includes(review.status)" class="mt-4 grid md:grid-cols-[200px_1fr_auto] gap-2"><select v-model="drafts[review.id].action" class="rounded-lg border-gray-300"><option>KEEP_ACCESS</option><option>REVOKE_ACCESS</option><option>MARK_APPROVED</option><option>MARK_REFUNDED</option><option>DISMISS</option></select><input v-model="drafts[review.id].notes" placeholder="Justificativa da decisão" class="rounded-lg border-gray-300"/><button :disabled="drafts[review.id].notes.length<3" @click="resolve(review)" class="rounded-lg bg-primary-600 text-white px-4 py-2 disabled:opacity-50">Resolver</button></div></article></div></section></div>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import Metric from '../components/OperationsMetric.vue'; import { claimFinancialReview, getFinancialSummary, listFinancialReviews, resolveFinancialReview } from '../api/financial'
const summary=ref({}); const reviews=ref([]); const loading=ref(true); const error=ref(''); const filter=ref(''); const drafts=reactive({}); const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
function initDrafts(){ for(const r of reviews.value) if(!drafts[r.id]) drafts[r.id]={action:'KEEP_ACCESS',notes:''} }
async function loadSummary(){ summary.value=(await getFinancialSummary()).data }
async function loadReviews(){ loading.value=true; try{ reviews.value=(await listFinancialReviews(filter.value?{status_filter:filter.value}:{})).data; initDrafts() }catch(e){ error.value=e.response?.data?.detail||'Erro ao carregar revisões.' }finally{ loading.value=false } }
async function claim(r){ try{ Object.assign(r,(await claimFinancialReview(r.id)).data) }catch(e){ error.value=e.response?.data?.detail||'Não foi possível assumir o caso.' } }
async function resolve(r){ try{ Object.assign(r,(await resolveFinancialReview(r.id,drafts[r.id])).data); await loadSummary() }catch(e){ error.value=e.response?.data?.detail||'Não foi possível resolver o caso.' } }
onMounted(async()=>{ try{ await Promise.all([loadSummary(),loadReviews()]) }catch(e){ error.value=e.response?.data?.detail||'Erro ao carregar financeiro.' } })
</script>
