<template>
  <div class="min-h-screen bg-[var(--surface-page)]"><AppNavbar />
    <main class="relative overflow-hidden"><div class="pointer-events-none absolute -right-32 top-20 h-96 w-96 rounded-full bg-[var(--brand-primary-soft)] blur-3xl"></div>
      <div class="relative mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-14 lg:px-8 lg:py-16"><div class="grid gap-8 lg:grid-cols-[1.05fr_.95fr] lg:items-stretch">
        <section class="overflow-hidden rounded-[26px] text-white shadow-2xl" data-testid="partner-proposition" :style="propositionStyle"><div class="relative flex h-full min-h-[560px] flex-col justify-between p-7 sm:p-9 lg:p-10"><div class="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-white/10"></div><div class="relative"><p class="text-xs font-bold uppercase tracking-[.2em] text-white/50">Plataforma corporativa</p><h1 class="mt-4 max-w-xl text-3xl font-bold leading-tight tracking-tight sm:text-4xl">Seja um parceiro</h1><p class="mt-4 max-w-xl text-base leading-7 text-white/70">Leve uma experiência de treinamento premium, personalizada com sua marca e preparada para gestão corporativa.</p></div>
          <div v-if="authVisual" class="relative my-8 aspect-video overflow-hidden rounded-2xl border border-white/10 shadow-xl" data-testid="partner-visual"><img :src="authVisual.src" :alt="authVisual.alt" class="absolute inset-0 h-full w-full object-cover"/><div class="absolute inset-0 bg-gradient-to-t from-slate-950/55 to-transparent"></div></div>
          <div class="relative grid gap-3 sm:grid-cols-3"><div v-for="benefit in benefits" :key="benefit.title" class="rounded-2xl border border-white/10 bg-white/[.08] p-4 backdrop-blur"><div class="flex h-9 w-9 items-center justify-center rounded-xl bg-white/10"><NavIcon :name="benefit.icon"/></div><h3 class="mt-3 text-sm font-bold">{{ benefit.title }}</h3><p class="mt-1 text-xs leading-5 text-white/55">{{ benefit.text }}</p></div></div></div></section>
        <section class="premium-card flex items-center p-6 sm:p-8 lg:p-10" data-testid="partner-form-card"><div class="w-full"><div v-if="submitted" class="py-10 text-center" data-testid="partner-success"><div class="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-600"><NavIcon name="shield"/></div><h2 class="mt-5 text-2xl font-bold text-slate-900">Proposta recebida!</h2><p class="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Sua proposta foi enviada com sucesso. Entraremos em contato pelo e-mail informado.</p><button @click="resetForm" class="mt-6 text-sm font-bold text-[var(--brand-primary)]" data-testid="partner-new-submission">Enviar nova proposta</button></div>
          <form v-else class="space-y-5" @submit.prevent="handleSubmit"><div><p class="premium-kicker">Fale com nosso time</p><h2 class="mt-2 text-2xl font-bold tracking-tight text-slate-900">Conte sobre sua empresa</h2><p class="mt-2 text-sm leading-6 text-slate-500">Vamos entender sua operação e estruturar o melhor modelo de treinamento.</p></div><div class="grid gap-4 sm:grid-cols-2"><label class="sm:col-span-2"><span class="mb-2 block text-sm font-semibold text-slate-700">Empresa *</span><input v-model="form.company_name" type="text" required class="w-full" data-testid="partner-company-input"/></label><label><span class="mb-2 block text-sm font-semibold text-slate-700">CNPJ</span><input v-model="form.cnpj" type="text" class="w-full" data-testid="partner-cnpj-input"/></label><label><span class="mb-2 block text-sm font-semibold text-slate-700">Nome do contato *</span><input v-model="form.contact_name" type="text" required class="w-full" data-testid="partner-contact-name-input"/></label><label><span class="mb-2 block text-sm font-semibold text-slate-700">E-mail *</span><input v-model="form.contact_email" type="email" required class="w-full" data-testid="partner-email-input"/></label><label><span class="mb-2 block text-sm font-semibold text-slate-700">Telefone</span><input v-model="form.contact_phone" type="text" class="w-full" data-testid="partner-phone-input"/></label><label class="sm:col-span-2"><span class="mb-2 block text-sm font-semibold text-slate-700">Mensagem</span><textarea v-model="form.message" rows="4" class="w-full" data-testid="partner-message-input"/></label></div><AppAlert v-if="error" type="error" data-testid="partner-error">{{ error }}</AppAlert><button type="submit" :disabled="loading" class="w-full rounded-xl py-3 text-sm font-bold text-white shadow-md transition hover:-translate-y-px disabled:opacity-50" :style="{background:'var(--brand-primary)'}" data-testid="partner-submit-btn">{{ loading ? 'Enviando...' : 'Enviar proposta' }}</button></form></div></section>
      </div></div></main>
    <footer class="bg-slate-950 py-8 text-center text-white/60"><img v-if="tenantStore.logo_white_url || tenantStore.logo_url" :src="tenantStore.logo_white_url || tenantStore.logo_url" :alt="tenantStore.name" class="mx-auto mb-3 h-8 w-auto max-w-[180px] object-contain"/><p class="text-xs">{{ tenantName }} — Treinamentos com certificação</p></footer>
  </div>
</template>
<script setup>
import { reactive, ref, computed } from 'vue'; import { submitPartnerLead } from '../api/partner'; import { useTenantStore } from '../stores/tenant'; import { getWrAuthVisual } from '../utils/courseMedia'; import AppAlert from '../components/AppAlert.vue'; import AppNavbar from '../components/AppNavbar.vue'; import NavIcon from '../components/NavIcon.vue'
const tenantStore=useTenantStore(),tenantName=computed(()=>tenantStore.name||'Plataforma de Cursos'),authVisual=computed(()=>getWrAuthVisual()); const propositionStyle=computed(()=>({background:`linear-gradient(145deg,${tenantStore.secondary_color||'#17324D'},${tenantStore.primary_color||'#1B7A3A'})`})); const benefits=[{icon:'layers',title:'Gestão completa',text:'Cursos, alunos, progresso e certificações em um só ambiente.'},{icon:'palette',title:'White Label',text:'Sua marca, cores e identidade em toda a experiência.'},{icon:'shield',title:'Certificação verificável',text:'Documentos digitais com validade e autenticação pública.'}]; const form=reactive({company_name:'',cnpj:'',contact_name:'',contact_email:'',contact_phone:'',message:''}),loading=ref(false),error=ref(''),submitted=ref(false);async function handleSubmit(){if(loading.value)return;loading.value=true;error.value='';try{await submitPartnerLead(form);submitted.value=true}catch(err){error.value=err.response?.data?.detail||'Erro ao enviar proposta. Tente novamente.'}finally{loading.value=false}}function resetForm(){Object.keys(form).forEach(k=>form[k]='');submitted.value=false;error.value=''}
</script>
