from __future__ import annotations

from datetime import timedelta
from uuid import UUID

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.utils import utc_now
from app.models.assessment import AssessmentAttempt
from app.models.compliance import (
    CourseComplianceProfile,
    PedagogicalProjectVersion,
    PracticalTrainingRecord,
    TrainingProfessional,
    TrainingSession,
)
from app.models.course import Course
from app.models.enrollment import Enrollment


class ComplianceNotReadyError(Exception):
    def __init__(self, blockers: list[str]):
        self.blockers = blockers
        super().__init__("; ".join(blockers))


class ComplianceService:
    """Fail-closed rules for official regulatory training/certification.

    A DEMO certificate may still be generated by the homologation flow. An
    official certificate for a course whose code starts with ``NR-`` is only
    eligible after an explicit, reviewed compliance profile satisfies all
    required evidence. Unknown facts never default to compliant.
    """

    @staticmethod
    def is_regulatory_course(course: Course) -> bool:
        return bool(course.code and course.code.upper().startswith("NR-"))

    @staticmethod
    async def get_profile(
        db: AsyncSession, *, tenant_id: UUID, course_id: UUID
    ) -> CourseComplianceProfile | None:
        return (
            await db.execute(
                select(CourseComplianceProfile).where(
                    CourseComplianceProfile.tenant_id == tenant_id,
                    CourseComplianceProfile.course_id == course_id,
                )
            )
        ).scalar_one_or_none()

    @staticmethod
    async def active_study_seconds(
        db: AsyncSession, *, tenant_id: UUID, enrollment_id: UUID
    ) -> int:
        value = await db.scalar(
            select(func.coalesce(func.sum(TrainingSession.active_seconds), 0)).where(
                TrainingSession.tenant_id == tenant_id,
                TrainingSession.enrollment_id == enrollment_id,
            )
        )
        return int(value or 0)

    @staticmethod
    async def official_certificate_blockers(
        db: AsyncSession,
        *,
        tenant_id: UUID,
        course: Course,
        enrollment: Enrollment,
    ) -> list[str]:
        if not ComplianceService.is_regulatory_course(course):
            return []

        blockers: list[str] = []
        profile = await ComplianceService.get_profile(
            db, tenant_id=tenant_id, course_id=course.id
        )
        if not profile:
            return ["Perfil regulatório do curso não cadastrado"]

        if profile.status != "COMPLIANCE_READY":
            blockers.append(
                f"Perfil regulatório não aprovado (status: {profile.status})"
            )
        if profile.blocker_reason:
            blockers.append(profile.blocker_reason)
        if not profile.regulatory_standard:
            blockers.append("Norma regulamentadora não identificada")
        if not profile.regulatory_version:
            blockers.append("Versão normativa não registrada")
        if not profile.normative_source_url:
            blockers.append("Fonte normativa oficial não registrada")
        if profile.source_checked_at is None:
            blockers.append("Fonte normativa ainda não teve data de conferência registrada")
        if profile.next_review_at and profile.next_review_at <= utc_now():
            blockers.append("Revisão regulatória vencida")

        course_mode = getattr(course.modality, "value", course.modality)
        if not profile.required_delivery_mode:
            blockers.append("Modalidade regulatória não validada")
        elif course_mode != profile.required_delivery_mode:
            blockers.append(
                f"Modalidade do curso ({course_mode}) incompatível com a modalidade exigida "
                f"({profile.required_delivery_mode})"
            )

        if not profile.technical_responsible_id:
            blockers.append("Responsável técnico não definido")
        else:
            professional = (
                await db.execute(
                    select(TrainingProfessional).where(
                        TrainingProfessional.id == profile.technical_responsible_id,
                        TrainingProfessional.tenant_id == tenant_id,
                        TrainingProfessional.is_active.is_(True),
                    )
                )
            ).scalar_one_or_none()
            if not professional:
                blockers.append("Responsável técnico inativo ou não encontrado")
            elif professional.professional_role != "TECHNICAL_RESPONSIBLE":
                blockers.append("Profissional indicado não está cadastrado como responsável técnico")
            elif not professional.qualification:
                blockers.append("Qualificação do responsável técnico não registrada")

        if not profile.pedagogical_project_version_id:
            blockers.append("Projeto pedagógico aprovado não vinculado")
        else:
            project = (
                await db.execute(
                    select(PedagogicalProjectVersion).where(
                        PedagogicalProjectVersion.id == profile.pedagogical_project_version_id,
                        PedagogicalProjectVersion.tenant_id == tenant_id,
                        PedagogicalProjectVersion.course_id == course.id,
                    )
                )
            ).scalar_one_or_none()
            if not project or project.status != "APPROVED":
                blockers.append("Projeto pedagógico não está aprovado")
            else:
                mandatory_project_fields = {
                    "objetivo geral": project.general_objective,
                    "princípios de SST": project.safety_principles,
                    "estratégia pedagógica": project.pedagogical_strategy,
                    "infraestrutura operacional": project.operational_infrastructure,
                    "público-alvo": project.target_audience,
                    "metodologia de avaliação": project.assessment_methodology,
                    "canal de dúvidas": project.support_channel,
                }
                missing = [label for label, value in mandatory_project_fields.items() if not value]
                if missing:
                    blockers.append(
                        "Projeto pedagógico incompleto: " + ", ".join(missing)
                    )
                if project.workload_hours is None:
                    blockers.append("Carga horária ausente no projeto pedagógico")
                if course_mode in ("EAD", "SEMIPRESENCIAL"):
                    if project.minimum_daily_dedication_minutes is None:
                        blockers.append("Dedicação diária mínima não definida para EAD/semipresencial")
                    if project.maximum_completion_days is None:
                        blockers.append("Prazo máximo de conclusão não definido para EAD/semipresencial")
                if project.valid_until and project.valid_until <= utc_now():
                    blockers.append("Projeto pedagógico venceu e precisa ser revisado")

        if not profile.support_channel_verified:
            blockers.append("Canal operacional para esclarecimento de dúvidas não validado")

        if profile.requires_final_assessment:
            if not profile.assessment_practical_scenarios_validated:
                blockers.append("Avaliação ainda não validada quanto a situações práticas da rotina laboral")
            attempt = (
                await db.execute(
                    select(AssessmentAttempt)
                    .where(
                        AssessmentAttempt.tenant_id == tenant_id,
                        AssessmentAttempt.enrollment_id == enrollment.id,
                        AssessmentAttempt.course_id == course.id,
                        AssessmentAttempt.passed.is_(True),
                        AssessmentAttempt.completed_at.is_not(None),
                    )
                    .order_by(AssessmentAttempt.completed_at.desc())
                    .limit(1)
                )
            ).scalar_one_or_none()
            if not attempt:
                blockers.append("Avaliação de aprendizagem satisfatória não encontrada")
            elif profile.minimum_score is not None and (attempt.score or 0) < profile.minimum_score:
                blockers.append("Avaliação não atingiu o critério mínimo do perfil regulatório")

        if profile.requires_practical_component:
            practical = (
                await db.execute(
                    select(PracticalTrainingRecord)
                    .where(
                        PracticalTrainingRecord.tenant_id == tenant_id,
                        PracticalTrainingRecord.enrollment_id == enrollment.id,
                        PracticalTrainingRecord.course_id == course.id,
                        PracticalTrainingRecord.result == "SATISFATORIO",
                    )
                    .order_by(PracticalTrainingRecord.occurred_at.desc())
                    .limit(1)
                )
            ).scalar_one_or_none()
            if not practical:
                blockers.append("Componente prático satisfatório não registrado")
            elif (
                profile.practical_minimum_percent is not None
                and (practical.practical_percent or 0) < profile.practical_minimum_percent
            ):
                blockers.append("Componente prático abaixo do percentual mínimo exigido")

        if profile.minimum_workload_hours:
            active_seconds = await ComplianceService.active_study_seconds(
                db, tenant_id=tenant_id, enrollment_id=enrollment.id
            )
            minimum_seconds = int(profile.minimum_workload_hours * 3600)
            if active_seconds < minimum_seconds:
                blockers.append(
                    f"Tempo ativo de capacitação insuficiente: {active_seconds // 60} min "
                    f"registrados de {minimum_seconds // 60} min exigidos"
                )

        # Preserve order while avoiding duplicate explanations.
        return list(dict.fromkeys(blockers))

    @staticmethod
    async def assert_official_certificate_eligible(
        db: AsyncSession,
        *,
        tenant_id: UUID,
        course: Course,
        enrollment: Enrollment,
    ) -> None:
        blockers = await ComplianceService.official_certificate_blockers(
            db,
            tenant_id=tenant_id,
            course=course,
            enrollment=enrollment,
        )
        if blockers:
            raise ComplianceNotReadyError(blockers)

    @staticmethod
    def retention_until(*, profile: CourseComplianceProfile | None, occurred_at=None):
        """NR-1 Annex II requires EAD access logs for >=2 years after course validity.

        When validity is unknown we return None, meaning the record must be held
        indefinitely until a reviewed retention rule exists. This is fail-closed.
        """
        base = occurred_at or utc_now()
        if not profile or not profile.periodicity_months:
            return None
        days = int(profile.periodicity_months * 30.4375) + 730
        return base + timedelta(days=days)
