"""
Seed data para cursos WR Consultoria.
Reconciliado com apostilas reais em agosto 2026.
Catálogo baseado em 47 PDFs únicos analisados via OCR.
"""

COURSES_DATA = [
    {"code": "BV-F", "name": "Brigada Voluntária", "category": "Complementares", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 249.9},
    {"code": "DD-F", "name": "Direção Defensiva", "category": "Complementares", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "GL-F", "name": "Ginástica Laboral", "category": "Complementares", "carga_horaria": 4, "modality": "EAD", "tipo_curso": "FORMACAO", "price": 79.9},
    {"code": "NR-01-F", "name": "NR 1 - Disposições Gerais e Gerenciamento de Riscos Ocupacionais", "category": "NR 01", "carga_horaria": 4, "modality": "EAD", "tipo_curso": "FORMACAO", "price": 79.9},
    {"code": "NR-05-F", "name": "NR 5 - CIPA - Comissão Interna de Prevenção de Acidentes", "category": "NR 05", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-06-F", "name": "NR 6 - Equipamento de Proteção Individual - EPI", "category": "NR 06", "carga_horaria": 4, "modality": "EAD", "tipo_curso": "FORMACAO", "price": 79.9},
    {"code": "NR-10-B", "name": "NR 10 - Segurança em Instalações e Serviços em Eletricidade - Básico", "category": "NR 10", "carga_horaria": 40, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 299.9},
    {"code": "NR-10-S", "name": "NR 10 - Segurança no Sistema Elétrico de Potência - SEP", "category": "NR 10", "carga_horaria": 40, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 299.9},
    {"code": "NR-11-EMP", "name": "NR 11 - Operador de Empilhadeira", "category": "NR 11", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 199.9},
    {"code": "NR-11-GUI", "name": "NR 11 - Operador de Guindauto", "category": "NR 11", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 199.9},
    {"code": "NR-11-MIN", "name": "NR 11 - Operador de Mini Carregadeira", "category": "NR 11", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 199.9},
    {"code": "NR-11-PLA", "name": "NR 11 - Operador de Plataforma Elevatória", "category": "NR 11", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 199.9},
    {"code": "NR-11-PON", "name": "NR 11 - Operador de Ponte Rolante", "category": "NR 11", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 199.9},
    {"code": "NR-11-RET", "name": "NR 11 - Operador de Retroescavadeira", "category": "NR 11", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 199.9},
    {"code": "NR-12-F", "name": "NR 12 - Máquinas e Equipamentos - Geral", "category": "NR 12", "carga_horaria": 12, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 199.9},
    {"code": "NR-17-ADM", "name": "NR 17 - Ergonomia para Atividades Administrativas", "category": "NR 17", "carga_horaria": 8, "modality": "EAD", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-17-CHK", "name": "NR 17 - Ergonomia para Operador de Checkout", "category": "NR 17", "carga_horaria": 8, "modality": "EAD", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-17-TEL", "name": "NR 17 - Ergonomia para Operador de Telemarketing/Teleatendimento", "category": "NR 17", "carga_horaria": 8, "modality": "EAD", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-17-TRA", "name": "NR 17 - Levantamento e Transporte Manual de Peso", "category": "NR 17", "carga_horaria": 8, "modality": "EAD", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-18-F", "name": "NR 18 - Condições e Meio Ambiente na Indústria da Construção", "category": "NR 18", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-20-AI", "name": "NR 20 - Inflamáveis e Combustíveis - Avançado I", "category": "NR 20", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-20-AII", "name": "NR 20 - Inflamáveis e Combustíveis - Avançado II", "category": "NR 20", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-20-BAS", "name": "NR 20 - Inflamáveis e Combustíveis - Básico", "category": "NR 20", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-20-ESP", "name": "NR 20 - Inflamáveis e Combustíveis - Específico", "category": "NR 20", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-20-INI", "name": "NR 20 - Inflamáveis e Combustíveis - Inicial", "category": "NR 20", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "INICIAL", "price": 149.9},
    {"code": "NR-20-INT", "name": "NR 20 - Inflamáveis e Combustíveis - Intermediário", "category": "NR 20", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-22-F", "name": "NR 22 - CIPAMIN - Segurança e Saúde na Mineração", "category": "NR 22", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-23-F", "name": "NR 23 - Proteção Contra Incêndios", "category": "NR 23", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-26-F", "name": "NR 26 - Sinalização de Segurança - Geral", "category": "NR 26", "carga_horaria": 4, "modality": "EAD", "tipo_curso": "FORMACAO", "price": 79.9},
    {"code": "NR-26-LAB", "name": "NR 26 - Sinalização de Segurança para Laboratório", "category": "NR 26", "carga_horaria": 4, "modality": "EAD", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-29-CPATP", "name": "NR 29 - CPATP - Comissão de Prevenção de Acidentes no Trabalho Portuário", "category": "NR 29", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-29-POR", "name": "NR 29 - Saúde e Segurança no Trabalho Portuário", "category": "NR 29", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-29-SIN", "name": "NR 29 - Sinaleiro - Sinalização Manual no Trabalho Portuário", "category": "NR 29", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-31-I", "name": "NR 31 - Saúde e Segurança no Trabalho Rural - Admissional", "category": "NR 31", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "INICIAL", "price": 149.9},
    {"code": "NR-31-AGR", "name": "NR 31 - Saúde e Segurança com Produtos Agrotóxicos", "category": "NR 31", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-31-CIPATR", "name": "NR 31 - CIPATR - Comissão Interna de Prevenção de Acidentes no Trabalho Rural", "category": "NR 31", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-31-P", "name": "NR 31 - Saúde e Segurança no Trabalho Rural - Periódico", "category": "NR 31", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "PERIODICO", "price": 149.9},
    {"code": "NR-32-F", "name": "NR 32 - Segurança e Saúde no Serviço de Saúde / Biossegurança", "category": "NR 32", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-33-AUT", "name": "NR 33 - Espaços Confinados - Trabalhador Autorizado", "category": "NR 33", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 249.9},
    {"code": "NR-33-SUP", "name": "NR 33 - Espaços Confinados - Supervisor", "category": "NR 33", "carga_horaria": 16, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 249.9},
    {"code": "NR-34-ADM", "name": "NR 34 - Segurança e Saúde no Trabalho Naval - Admissional", "category": "NR 34", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "INICIAL", "price": 149.9},
    {"code": "NR-34-PER", "name": "NR 34 - Segurança e Saúde no Trabalho Naval - Periódico", "category": "NR 34", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "PERIODICO", "price": 149.9},
    {"code": "NR-35-F", "name": "NR 35 - Trabalho em Altura", "category": "NR 35", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "NR-36-F", "name": "NR 36 - Segurança e Saúde em Frigoríficos / Abate e Processamento de Carnes", "category": "NR 36", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
    {"code": "PCA-F", "name": "Programa de Conservação Auditiva - PCA", "category": "Programas", "carga_horaria": 4, "modality": "EAD", "tipo_curso": "FORMACAO", "price": 79.9},
    {"code": "PPR-F", "name": "Programa de Proteção Respiratória - PPR", "category": "Programas", "carga_horaria": 4, "modality": "EAD", "tipo_curso": "FORMACAO", "price": 79.9},
    {"code": "PS-F", "name": "Primeiros Socorros", "category": "Programas", "carga_horaria": 8, "modality": "SEMIPRESENCIAL", "tipo_curso": "FORMACAO", "price": 149.9},
]
