[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --cov=app --cov-report=term-missing --cov-report=xml --cov-fail-under=75
filterwarnings =
    ignore:.*crypt.*:DeprecationWarning:passlib.*
    ignore:.*argon2.*:DeprecationWarning:passlib.*
    ignore:.*datetime.datetime.utcnow.*:DeprecationWarning:jose.*
